[package]
name = "rand_rect"
version = "0.1.1"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", ] }
rand = "*"
extras = { path = "../../extras" }