[package]
name = "colors1"
version = "0.1.1"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "commctrl", ] }
extras = { path = "../../extras" }
