[package]
name = "sys_mets3"
version = "0.1.2"
authors = ["recombinant <gituser@recombinant.me.uk>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", ] }
sys_mets_data = { path = "../sys_mets_data" }
extras = { path = "../../extras" }