[package]
name = "head"
version = "0.1.2"
authors = ["recombinant <gituser@recombinant.me.uk>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "commctrl", "processenv", "handleapi" ] }
extras = { path = "../../extras" }

