[package]
name = "checker2"
version = "0.1.2"
authors = ["recombinant <gituser@recombinant.me.uk>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser", "winbase", "windowsx", ] }
extras = { path = "../../extras" }
