[package]
name = "extras"
version = "0.1.1"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser", "winbase", "windowsx", "winnls"] }
