[package]
name = "dig_clock"
version = "0.1.2"
authors = ["recombinant <gituser@recombinant.me.uk>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["libloaderapi", "sysinfoapi", ] }
extras = { path = "../../extras" }
